import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Toaster } from "react-hot-toast";

const inter = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased debug-screens bg-black-500 min-h-screen text-white leading-relaxed`}
      >
        <Toaster />
        <nav className="border-b-[0.5px] border-white/15">
          <div className="container mx-auto p-6">
            <Link href="/">
              <h1 className="font-semibold text-xl transition-colors text-teal-600 hover:text-white">
                Streaming
              </h1>
            </Link>
          </div>
        </nav>

        {children}
      </body>
    </html>
  );
}
